name = "FdeSolver"
uuid = "8bc876f4-fe3d-4645-ab4f-574d4c5ada41"
authors = ["Moein Khalinghi and Giulio Benedetti <giuliobene2000@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
