name = "FdeSolver"
uuid = "1746e360-1058-44a5-9855-ddd460437d0c"
authors = ["Moein Khalighi", "Giulio Benedetti", "Leo Lahti"]
version = "1.0.7"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
FFTW = "1.2"
SpecialFunctions = "1, 2"
julia = "^1"

[extras]
MittagLeffler = "9c257583-4f8f-53fd-abd9-c69d5080dd54"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
examples = ["Plots", "MittagLeffler"]
test = ["Test", "SafeTestsets", "Statistics"]
docs = ["Plots", "SpecialFunctions"]
