name = "FdeSolver"
uuid = "1746e360-1058-44a5-9855-ddd460437d0c"
authors = ["Moein Khalighi", "Giulio Benedetti"]
version = "0.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
LinearAlgebra = "1.0"
SpecialFunctions = "0.9 - 1.6.2"
julia = "1.4"

[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
examples = ["Plots"]
test = ["Test", "SafeTestsets", "Statistics"]
