name = "FdeSolver"
uuid = "1746e360-1058-44a5-9855-ddd460437d0c"
authors = ["Moein Khalighi", "Giulio Benedetti"]
version = "0.1.0"

[deps]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
julia = "1"

[extras]
MittagLeffler = "9c257583-4f8f-53fd-abd9-c69d5080dd54"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
examples = ["Plots", "MittagLeffler"]
test = ["Test", "SafeTestsets", "MittagLeffler"]
