name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'docs/**'
      - 'src/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: julia-actions/setup-julia@v1
      with:
        version: '1.x'
    - name: Install dependencies
      run: julia --project=docs/ -e 'using Pkg; Pkg.instantiate()'
    - name: Build and deploy documentation
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: julia --project=docs/ docs/make.jl
